### ISSUE TITLE
Product Management : Delete/Update Product

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#10]
As a **admin** I can **Update and delete selected product** so that **admin have the control to manage the products based on business need**

## Acceptance Criteria

*  For admin show  'delete and update' link in the product detail template 
*  Show the update product form with required fields 

## Task
- [ ] Create product update form template with all necessary fields
- [ ] Create product delete confirmation message before deleting the product
- [ ] Show the success message.
- [ ] Test functionalities
