### ISSUE TITLE
Product Management : Manage Category

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#11]
As a **admin** I can **edit/delete/update category** so that **admin can manage the business well**

## Acceptance Criteria

* For admin, show manage category option in shop dropdown list
*  Show manage category form template ,list all available categories with delete/update and add link
*  Show form template for add, delete and update category

## Task 
- [ ] Create manage category option in the shop dropdown list
- [ ] Create Manage category form template with add option and list all available categories with update/delete option.
- [ ] Create form template for add, delete and update category 
- [ ] Create success message 
- [ ] Test functionalities
