### ISSUE TITLE
Product Management : Manage Brand

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#12]
As a **admin** I can **edit/delete/update brand** so that **admin can manage the business well**

## Acceptance Criteria

* For admin, show manage brand option in brand dropdown list
*  Show manage brand form template ,list all available brands with delete/update and add link
*  Show form template for add, delete and update brand

## Task 
- [ ] Create manage brand option in the brands dropdown list
- [ ] Create Manage brand form template with add option and list all available brands with update/delete option.
- [ ] Create form template for add, delete and update brand 
- [ ] Create success message 
- [ ] Test functionalities
