### ISSUE TITLE
Viewing and Navigation : View individual product details 

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#13]
As a **site user** I can **view individual product details** so that **I can decide to buy the product**

## Acceptance Criteria

* Show the 'Detail' link on each product image
* Show Product detail template with product description, price, rating and available size.
*  Show option to add to cart , go to bag and continue shopping  

## Task

- [ ] Create wireframe 
- [ ] Create Detail link on the product image
- [ ] Create product details template with product description, price, rating and available size
- [ ] Create option add to cart, go to bag and continue shopping
- [ ] Test functionality
