### ISSUE TITLE
Viewing and Navigation : View shopping cart item count

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#15]
As a **shopper** I can **view the total cart item easily** so that **I can manage my expenditure**

## Acceptance Criteria

* Show total no of cart items on the navbar 

## Task
- [ ] Create cart icon on the navbar to display the total no of items in the cart
- [ ] Increment the count by adding the items to shopping cart
- [ ] Test the functionality
