### ISSUE TITLE
Sorting and Searching : Sort specific category of product

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#16]
As a **shopper** I can **sort the products based on category** so that **I can browse very specific product**

## Acceptance Criteria

* List different categories under shop dropdown link
* List different categories on all product list
* Display all products specific to selected category

## Task 

- [ ] Create list of product categories and display under shop dropdown menu on navbar
- [ ] Create list of product categories and display on all product template
- [ ] Create template for displaying all product specific to selected category 
- [ ] Test the functionalities
