### ISSUE TITLE
Sorting and Searching : Sort product based on ascending/ descending order of name

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#17]
As a **shopper** I can **sort the products based on ascending/ descending order of name** so that **I can browse products very easily**

## Acceptance Criteria

* Give option to order the product based on ascending/ descending on all products template
* Display the products ascending/descending order of product names  

## Task 

- [ ] Create order by option on all products template
- [ ] Create template for displaying the product  ascending/descending order of product names  
- [ ] Test the functionalities
