### ISSUE TITLE
Sorting and Searching : Sort product based on the price ascending/ descending order

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#18]
As a **shopper** I can **sort the products based on ascending/ descending order of price** so that **I can browse products very easily**

## Acceptance Criteria

* Give option to order the product based on ascending/ descending of their price on all products template
* Display the products ascending/descending order of product price  

## Task 

- [ ] Create order by option on all products template
- [ ] Create template for displaying the product  ascending/descending order of product price  
- [ ] Test the functionalities
