### ISSUE TITLE
Sorting and Searching : Display searched results

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#20]
As a **shopper** I can **see the number of results along with the search name ** so that **I can decide the required product is available or not**

## Acceptance Criteria

* Show the total no of searched results 
* Show the searched name on the result template

## Task

- [ ] Create template for displaying the searched results 
- [ ] Create placeholder for displaying the total no of results and searched  item
- [ ] Test the functionalities
