### ISSUE TITLE
Purchasing and Checkout : Select product size and quantity 

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#21]
As a **shopper** I can **select the size and quantity of the product** so that **I can easily buy suitable product and quantity**

## Acceptance Criteria

* Show available product size and option to select the quantity on product detail template
* Shopper prevent to add more quantity of product than in the product inventory
* Show out of stock if the sufficient quantity of the  product is not available 

## Task

- [ ] Create product details template with list of available product size and  option to select the quantity of product
- [ ] Create message to show out of stock 
- [ ] Check the shopper selected quantity is available in the product inventory table
- [ ] Test the functionality
