### ISSUE TITLE
Purchasing and Checkout : View shopping bag

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#22]
As a **shopper** I can **view the products in the shopping bag** so that **I can cross check all the products and total cost**

## Acceptance Criteria

* Show all the products in shopping cart
* Show price , option to increase/decrease the quantity in the shopping cart
* Display delete option against each product in the shopping cart
* Display total cost 

## Task 

- [ ] Create shopping cart template 
- [ ] Create placeholder for showing the product name, price and quantity on the template
- [ ] Create an option to increase/decrease the quantity in the shopping cart
- [ ] Create delete link against each product listing in the shopping cart
- [ ] Test the functionality
