### ISSUE TITLE
Purchasing and Checkout : Adjust the quantity of the item in shopping bag

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#23]
As a **shopper** I can **modify the number of items to purchase** so that **I can control the my budget**

## Acceptance Criteria

* Show price , option to increase/decrease the quantity in the shopping cart

## Task 
- [ ] Create shopping cart template
- [ ] Create an option to increase/decrease the quantity in the shopping cart
- [ ] Test the functionality
