### ISSUE TITLE
Purchasing and Checkout : Delete item from shopping bag

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#24]
As a **shopper** I can **delete item from shopping bag** so that **I can manage my budget**

## Acceptance Criteria

* Display delete option against each product in the shopping cart

## Task 

- [ ] Create shopping cart template
- [ ] Create delete link against each product listing in the shopping cart
- [ ] Test the functionality
