### ISSUE TITLE
Purchasing and Checkout : Checkout product to buy

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#25]
As a **shopper** I can **checkout the product** so that **I can enter the payment information**

## Acceptance Criteria

* Show the checkout option in the product detail 
* Show Payment details form on checkout template 
* Show delivery address form on checkout template

## Tasks

- [ ] Create template for product details with checkout link
- [ ] Create checkout template 
- [ ] Create forms for delivery address and payment 
- [ ] Test the functionalities
