### ISSUE TITLE
Purchasing and Checkout : Order confirmation

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#27]
As a **shopper** I can **view the order confirmation** so that **I can make sure my order placed successfully**

## Acceptance Criteria

* Show order confirmation with order number, delivery address, name, date of order , product list and total cost
* Order conformation template should have  continue shopping and My profile links

## Tasks

- [ ] Create template for order confirmation with  order number, delivery address, name, date of order , product list and total cost
- [ ] Create continue shopping and My profile links\
- [ ] Test the functionalities
