### ISSUE TITLE
Viewing and Navigation : Course List

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#5]
As a **site user** I can **view  all the courses** so that **I can book the course**

## Acceptance Criteria

* Course link on the navbar
* List all courses under the course 

## Task 

- [ ] Create course dropdown link on the navbar
- [ ] List all the courses
- [ ] Test the functionality
