### ISSUE TITLE
Product Management : Create Course

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#7]
As a **admin** I can **create a course ** so that **admin have the control to manage the courses based on business need **

## Acceptance Criteria

*  Show 'create product' link in the shop dropdown
*  Create product form template with all necessary fields
*  Show the success message and list the product in the available product lsit

## Task

- [ ] Create a link 'Create product' under shop dropdown
- [ ] Create Add product form template with all necessary fields
- [ ] Create success message
- [ ] Test functionality
