### ISSUE TITLE
Product Management : Create Product 

### ISSUE THREAD

**Issue by bijokmathew** [bijokmathew/DolphinSwimAcadamy#8]
As a **admin** I can **create a product** so that **admin have the control to manage the product based on business need**

## Acceptance Criteria

*  Show 'create product' link in the shop dropdown
*  Create product form template with all necessary fields
*  Show the success message and list the product in the available product list

## Task

- [ ] Create a link 'Create product' under shop dropdown
- [ ] Create Add product form template with all necessary fields
- [ ] Create success message
- [ ] Test functionality
